box      = 'hashicorp/precise64'
hostname = 'myprecisebox'
ip       = '10.10.10.10'
ram      = '2048'
cpus     = '2'

Vagrant.configure(2) do |config|
  config.vm.box = box
  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
  config.vm.provision :shell, :path => "provision.sh"

  #config.vm.network "private_network", ip: ip
  #config.vm.synced_folder "./", "/var/www", create: true, group: "www-data", owner: "www-data", type: "smb"
  config.vm.synced_folder "./", "/var/www", create: true, group: "www-data", owner: "www-data", type: "nfs"

  config.vm.provider "virtualbox" do |vb|
    vb.customize [
        'modifyvm', :id,
        '--name', hostname, 
        '--memory', ram, 
        '--cpus', cpus, 
        '--ioapic', 'on'
    ]
  end
end
